#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 2049BBS

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png


# Pagination
paginate: 24

collections:
  category_info:
    output: true
    permalink: /n/:name
  users:
    output: true
    permalink: /member/:name

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
  - scope:
      path: ""
      type: category_info
    values:
      layout: category
  - scope:
      path: ""
      type: users
    values:
      layout: user
  - scope:
      path: "feed"
    values:
      layout: feed
      is_category_feed: true

#
# !! You don't need to change any of the configuration flags below !!
#

timezone: Asia/Shanghai

permalink: /t/:title
paginate_path: /index/page:num

# The release of Jekyll Now that you're using
version: v3.8.5

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Transliterate the header text before generating the ID
  transliterated_header_ids: true
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

strict_front_matter: true

liquid:
  error_mode: strict

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-paginate
  - jekyll-github-metadata
# - jekyll-sitemap
# - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - Rakefile
  - "*.Rmd"
  - vendor
  - .travis.yml
  - "*.enc"
  - node_modules
  - tmp
  - backup.js
  - package.json
  - package-lock.json
